### PR TITLE
MNT: miscellaneous changes

### PR DESCRIPTION
**Pull request by tacaswell**
Found this branch on my computer but have no memory of doing it

### CODE REVIEW

**Comment by klauer** [comment]
Should this be closed or looked at more closely, @tacaswell?

**Comment by danielballan** [comment]
Bump @tacaswell

**Comment by tacaswell** [comment]
Looked at more closely.

**Comment by klauer** [comment]
Added miscellaneous test changes to your miscellaneous changes while I debugged miscellaneous local issues. Let's see what happens.

**Comment by danielballan** [comment]
GitHub should add a [Glomar response](https://en.m.wikipedia.org/wiki/Glomar_response) option for reviews.

**Comment by klauer** [comment]
Will merge once this last test re-run passes.

**Pull request merged**
