### PR TITLE
FIX: convert arrays to native endianess in pyepics_compat

### PR DESCRIPTION
**Pull request by tacaswell**
Alternative to https://github.com/bluesky/ophyd/pull/1186

### CODE REVIEW

**Comment by cjtitus** [comment]
I tested this and it works. Along the way, it illuminated for me why this only popped up in containers. It turns out that Ophyd is falling back on Caproto as the control layer, presumably because I haven't installed pyepics. And _caproto_shim.py does indeed call the pyepics_compat in Ophyd.

So presumably the _caproto_shim in Ophyd never gets used at NSLS-II because we always run in these massive Conda environments that have pyepics, but this could actually pop up somewhere else if someone's installing a more minimal environment from scratch.

**Review by klauer — APPROVED** [review]
Seems good to me

Where'd you find a big endian device?

**Comment by tacaswell** [comment]
conflict was trivial (two tests added at the bottom of the file).

**Comment by tacaswell** [comment]
Merging on @klauer 's approval.

**Pull request merged**
