### PR TITLE
API/FIX/CLN: do not track search requests on server; remove curio and trio clients

### PR DESCRIPTION
**Pull request by tacaswell**
The search related API was removed from :class:`ca.Broadcaster`, all
of the search request accounting is handled in the client code.  The
code that is used on the servers can not do this book keeping because
we can not know what other servers are out there and if the
SearchRequest actually got serviced (as that goes back uni-cast).

partially addresses #647

The tests I removed may need to be put back directly testing `ThreadsafeCounter`?

### CODE REVIEW

**Comment by tacaswell** [comment]
The curio client used the base Broadcaster search logic :(

**Comment by danielballan** [comment]
I would be OK with removing the experimental and very incomplete curio and trio clients until we get a chance to rebuild them in the fashion of our asyncio client.

**Comment by tacaswell** [comment]
I think the fix is relatively straight forward (copy the search logic from asyncio -> curio?).  We probably should go over the search functionality in all of the clients because they are each a bit different at this point....

**Comment by klauer** [comment]
Despite all of my efforts to keep curio/trio clients from breaking things, I'm on board with just nuking them for now.

**Comment by klauer** [comment]
Removed and tests are passing. Did not look much into docs, though.

**Review by danielballan — APPROVED** [review]
The docs changes you made look great. Very clear. There were no curio or trio client docs to remove or update.

@tacaswell might be right that just fixing the curio and trio clients by copy/pasting the broadcaster logic might be _easier_ than excising those clients, but they are so far out of sync with the functionality and APIs of the other clients that I think removing them is the right thing to do. Thanks for doing the work.

**Comment by tacaswell** [comment]
I did almost no work here...

**Pull request merged**
