### PR TITLE
improve mock 'ai' record compliance to 'real' EPICS record 

### PR DESCRIPTION
**Pull request by baldwinb**
Changed records.py so that common pv strings favors string type instead of char type. (Refer to mock record issue).

Added a test function that fetches real 'ai' record fields from the web and types, and then:
-compares types between mock ai and real ai
-ensures that all the mock fields can be read
-ensures any mock record enums can be read
-reads "PV$" as a string, and "PV" (without "$") as native type, (reflecting how EPICS would normally perform these reads)

You can test separately by "pytest test_ai_compliance.py", showing differences/problems with the mock record.

See related issue: https://github.com/caproto/caproto/issues/537

### CODE REVIEW

**Comment by tacaswell** [comment]
Thanks for this!  

Do we have to use pyepics in the tests or can we use the caproto threading client?

The test failures look like conflicts between {pytest, trio, attrs}.

**Comment by baldwinb** [comment]
I think that is fine if it gives the same errors.

The python test I wrote highlights the same problems that I observed when trying to read the pvs using our real epics ui; "pv properties" ( https://qtepics.github.io/ ).

"pv properties" polls all the .* PVs of a record for display in a list using real epics. When the ui is opened it showed:
-errors generated in the caproto server stdout/err (I originally ran in debug, via windows with asyncio)
-in particular with STAT enum, read issues on MDEL and ADEL
-RTYP is returned as char array, which the gui uses to decide which other .* PVs to look for. ie returns [97, 105] instead of 'ai'. ( the ui also tries to read RTYP$ which did not work at the time)

 If you run the test function without pytest you can see it is not a pytest issue. You could also try on a "real" record (which I did and had one short <> long error for ROFF, which is typically not used).

I am not sure there is a consequence of difference in type between short and long (probably not for us) but I have left it in as a fail because it is technically not compliant.

**Comment by klauer** [comment]
Merged as part of #577 - thanks @baldwinb!

**Comment by danielballan** [comment]
:tada:

**Pull request merged**
