### PR TITLE
WIP: Log cache sizes in telemetry loop.

### PR DESCRIPTION
**Pull request by danielballan**
Just a start -- making public early to facilitate coordination with related efforts by @klauer, @tacaswell 

- [ ] Actually run the telemetry_loop in the respective server implementations
- [ ] Additional info beyond cache sizes

### CODE REVIEW

**Comment by danielballan** [comment]
Now my intent is to do this via PVs rather than logging, incorporated in the structure laid out by #649. Leaving open as documentation of the sketch until I get time to incorporate it.

**Comment by danielballan** [comment]
@klauer I had intended to incorporate this in `StatsHelper` but I think it will run into the same limitation as [discussed here](https://github.com/caproto/caproto/pull/649#discussion_r494592502): it needs access to server state that we don't currently provide and may not _want_ to provide.

Given that should we:

1. Punt on this, deciding that the the tracemalloc stats are sufficient to debug runaway caches and that we don't want to take on an extra polling task and associated complexity in the code and logging output
2. Go ahead and implement this as originally suggestion
3. Open an issue to revisit this if we ever sort out how to cleanly let ChannelData / pvproperty access server state.

I am pretty ambivalent.

**Comment by klauer** [comment]
I'm somewhat leaning toward (2), or maybe my tacked-on alternative (4) below.

(4) It'd be nice to have this exact information in some easy-to-access way. If/when we ever get the REPL-like interface going (or the originally proposed `SIGINFO`), we could then query the server state easily with a method such as what you've already written (sans the loop and threshold checking).

**Comment by danielballan** [comment]
I like (4). Let’s push on that and then circle back here.

**Comment by danielballan** [comment]
I'm going to close this because it's lower behind a lot of other things I'm more likely to work on for caproto.

**Pull request closed without merging**
