### PR TITLE
Fixed broken link to Caproto documentation

### PR DESCRIPTION
**Pull request by dmgav**
Fixed broken link to documentation in README.md file

### CODE REVIEW

**Comment by dmgav** [comment]
I believe that this is the current link to the documentation for Caproto.
There is also a broken link to Travis CI badge.

**Comment by klauer** [comment]
Sorry, I had meant: https://caproto.github.io/caproto/

**Comment by danielballan** [comment]
Thanks, @dmgav. Good catch. Yes, https://caproto.github.io/caproto/ is the new canonical URL, and https://nsls-ii.github.io/caproto/doc is still maintained as a mirror but should eventually be replaced by a redirect when we get around to it.

**Comment by danielballan** [comment]
Since a working link is better than a broken link, I'll merge this now. Would you mind pushing a follow-up PR to update it to the canonical URL?

**Pull request merged**
