### PR TITLE
TST: make trio and curio optional at the test level

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Review by danielballan — APPROVED** [review]

**Comment by mguijarr** [comment]
+1 for this one

**Comment by tacaswell** [comment]
"powerecycled" to re-run tests.

```
~/s/b/c/caproto master|✓
✔ 15:03:05 [belanna] @ ack 'import trio'
caproto/examples/trio_server_simple.py
3:import trio

caproto/tests/conftest.py
737:    import trio

caproto/tests/epics_test_utils.py
77:        import trio

caproto/trio/util.py
2:import trio

caproto/trio/server.py
4:import trio
~/s/b/c/caproto mnt/optional_frameworks|✓
✔ 15:03:42 [belanna] @ ack 'from trio'
caproto/trio/server.py
5:from trio import socket
```

I think all of the trio imports are now  either in modules that are explicitly for trio or buried.  The tests pass for me locally in an env without trio installed.

**Review by mrakitin — APPROVED** [review]
Looks good to me!

**Comment by mrakitin** [comment]
Power-cycled to restart the CI (Win/Py312 build was failing.)

**Review by klauer — APPROVED** [review]
Seems good to me 👍

**Pull request merged**
