### PR TITLE
Example: an IOC with an asyncio client.

### PR DESCRIPTION
**Pull request by danielballan**
Example:

```
# Start any IOC.
python -m caproto.ioc_examples.random_walk 
```

```
# Start mirror IOC and provide it a "target" PV to mirror.
python -m caproto.ioc_examples.mirror --target random_walk:x
```

```
# Monitor the mirror.
$ caproto-monitor mirror:value
mirror:value                              2020-09-23 22:07:38.115205 [1.47088]
mirror:value                              2020-09-23 22:07:41.115865 [2.14317]
mirror:value                              2020-09-23 22:07:44.117169 [2.14567]
```

### CODE REVIEW

**Comment by danielballan** [comment]
Note to self: The `Context` can and should be defined at `__init__` time. The rest needs to happen inside a running event loop.

**Review by klauer — APPROVED** [review]
Maybe an additional example for status/severity mirroring and disconnection info as in https://github.com/caproto/caproto/blob/c7ef7bee8c70c5984f01425c5904aa9e99046e45/caproto/ioc_examples/thread_client_monitor.py#L142-L161?

**Comment by danielballan** [comment]
Good additions. I haven’t had time to circle back to address your suggestion. Feel free to make an issue or wait for merging—either is fine by me.

**Comment by klauer** [comment]
Seems good enough.

**Comment by klauer** [comment]
IOC example not in test suite so it can have no bearing on tests. Have tested locally. Merging.

**Pull request merged**
