### PR TITLE
REF: Use selector data to reduce threading client selector lookups

### PR DESCRIPTION
**Pull request by klauer**
This uses selector API I overlooked to simplify the lookup of `ready socket -> ready object`.

### CODE REVIEW

**Comment by klauer** [comment]
This PR is pretty simple, but I've added an additional fix to remove misbehaving sockets in 2026ac1b, as I see this on exit in CI: 

```
Exception in thread selector:

Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/python/3.6.7/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/build/caproto/caproto/caproto/threading/client.py", line 295, in __call__
    if obj.received(bytes_recv, address) is ca.DISCONNECTED:
  File "/home/travis/build/caproto/caproto/caproto/threading/client.py", line 1355, in received
    self._process_command(c)
  File "/home/travis/build/caproto/caproto/caproto/threading/client.py", line 1398, in _process_command
    self._disconnected()
  File "/home/travis/build/caproto/caproto/caproto/threading/client.py", line 1530, in _disconnected
    for chan in self.channels.values()))
  File "/home/travis/build/caproto/caproto/caproto/threading/client.py", line 1077, in reconnect
    self.broadcaster.search(self._search_results_queue, names)
  File "/home/travis/build/caproto/caproto/caproto/threading/client.py", line 507, in search
    self._register()
  File "/home/travis/build/caproto/caproto/caproto/threading/client.py", line 396, in _register
    self.send(ca.EPICS_CA2_PORT, command)
  File "/home/travis/build/caproto/caproto/caproto/threading/client.py", line 457, in send
    self.udp_sock.sendto(bytes_to_send, (host, specified_port))
AttributeError: 'NoneType' object has no attribute 'sendto'
```

If controversial, that can be removed.

**Comment by klauer** [comment]
Walking that back slightly:

```python
Traceback (most recent call last):
  File "/home/travis/build/caproto/caproto/caproto/_broadcaster.py", line 127, in recv
    commands = read_datagram(byteslike, address, self.their_role)
  File "/home/travis/build/caproto/caproto/caproto/_commands.py", line 301, in read_datagram
    _class = Commands[role][header.command]
KeyError: 24

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/python/3.6.7/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/build/caproto/caproto/caproto/threading/client.py", line 296, in __call__
    if obj.received(bytes_recv, address) is ca.DISCONNECTED:
  File "/home/travis/build/caproto/caproto/caproto/threading/client.py", line 574, in received
    commands = self.broadcaster.recv(bytes_recv, address)
  File "/home/travis/build/caproto/caproto/caproto/_broadcaster.py", line 130, in recv
    f' {ex.__class__.__name__} {ex}') from ex

caproto._utils.RemoteProtocolError: Broadcaster malformed packet received: KeyError 24
```

UDP receive failure shouldn't cause the socket to be removed, I don't think.

**Comment by tacaswell** [comment]
Can we fully drop `id_to_socket` and `socket_to_id` now as well?

To clarify, the extra try/except is a bug-fix to a bug that is not induced by the other changes?

**Comment by klauer** [comment]
It can be further cleaned up, for sure.

Yes, the additional try/except is for "don't let single socket exception take down entire client selector"

**Comment by klauer** [comment]
I (think) I had left the dictionaries in to keep track of sockets in the failing #588, but a simple integer count might suffice.

**Pull request merged**
