### PR TITLE
Raise ValueError when assigning a startup if one already exists.

### PR DESCRIPTION
**Pull request by ronpandolfi**
In response to https://github.com/caproto/caproto/issues/691

### CODE REVIEW

**Review by danielballan — APPROVED** [review]
Will merge in the next day or two unless @klauer has concerns.

**Comment by danielballan** [comment]
Worth checking whether this breaks overriding startup in subclass. I don’t think it does but there be magick here....

**Comment by klauer** [comment]
I think it might break easy subclassing and overriding of startup methods - that should be tested before proceeding.

**Review by danielballan — CHANGES_REQUESTED** [review]
With fresh eyes, updating my review in accordance with my later comment and @klauer's.

**Comment by klauer** [comment]
Need some more work on this one - it'll have to wait for the next minor tag.

I'm not sure how to differentiate the user's intent: "I want to override the startup method" versus "I accidentally assigned a startup method _and_ a scan method". Perhaps we could just support both `startup` and `scan`, since on the surface they don't seem like they should be exclusive to one another.

**Comment by danielballan** [comment]
Yeah, I had the same thought.

**Comment by klauer** [comment]
#729 intends to supersede this PR. Would it be OK to close this, @ronpandolfi?

**Comment by klauer** [comment]
#729 is merged and hopefully an agreeable resolution. Closing.

**Pull request closed without merging**
