### PR TITLE
TST: pytest_benchmark -> pytest-benchmark

### PR DESCRIPTION
**Pull request by klauer**
On conda-forge: pytest-benchmark-3.2.3
On pypi: https://pypi.org/project/pytest-benchmark/

### CODE REVIEW

**Comment by klauer** [comment]
Excellent question...

**Comment by tacaswell** [comment]
https://pypi.org/project/pytest_benchmark/ redirects so I wonder if they changed the same at some point?

**Comment by danielballan** [comment]
I believe that PyPI always redirects `-` <-> `_`. It respects however the project chooses its canonical spelling and does not allow projects to have the same name modulo `-`/`_`.

**Comment by klauer** [comment]
PyPI and conda differ in this regard as `_` and `-` are considered distinct. I noticed this while creating a conda environment from `test-requirements.txt`.

**Pull request merged**
