### PR TITLE
ENH/FIX: get_pv_pair_wrapper kwargs

### LINKED ISSUE #477: The pvproperty_with_rbv pattern doesn't work for Enum type
Seems like this pattern uses PVSpec, which doesn't accept this kwarg?
`enable = pvproperty_with_rbv(name='EnableCallbacks', value='no', enum_strings=['no', 'yes'], dtype=ChannelType.ENUM)`

...gives error:

```
Traceback (most recent call last):
  File "/home/rp/PycharmProjects/caproto/caproto/ioc_examples/areadetector_image.py", line 37, in <module>
    class DetectorGroup(PVGroup):
  File "/home/rp/PycharmProjects/caproto/caproto/ioc_examples/areadetector_image.py", line 204, in DetectorGroup
    class ImagePluginGroup(PVGroup):
  File "/home/rp/PycharmProjects/caproto/caproto/ioc_examples/areadetector_image.py", line 261, in ImagePluginGroup
    enable = pvproperty_with_rbv(name='EnableCallbacks', value='no', enum_strings=['no', 'yes'], dtype=ChannelType.ENUM)
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 814, in wrapped
    prefix=name,
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 684, in __init__
    self.group = group
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 695, in group
    self.group_dict = group
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 750, in group_dict
    self._class_dict = self._generate_class_dict()
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 732, in _generate_class_dict
    for attr, pvspec in self._group_dict.items()]
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 732, in <listcomp>
    for attr, pvspec in self._group_dict.items()]
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 721, in _pvspec_from_info
    return PVSpec(**info)
TypeError: __new__() got an unexpected keyword argument 'enum_strings'
```

### PR DESCRIPTION
**Pull request by klauer**
Hopefully closes #477

### CODE REVIEW

**Comment by klauer** [comment]
Could also consider special kwarg handling for record mocking: `mock_record=['ai', 'ao']` or `setpoint_record='ao', readback_record='ai'`, or ...

**Comment by tacaswell** [comment]
Did this get replaced with something else?

**Comment by klauer** [comment]
Unclear if this still works; needs testing

**Comment by klauer** [comment]
Unrelated test failures, and I'm getting impatient waiting.

Let's close that 2019 issue before 2021 gets here.

**Pull request merged**
