### PR TITLE
FIX: add a lock to sending over a VirtualCircuit

### PR DESCRIPTION
**Pull request by tacaswell**
This fixes a bug when:
 - there is a ReadResponse that `sock_sendall` can not send in on go
 - there is a monitor that will fire during that readout

Because the buffer for the ReadResponse is sent in parts, the bytes
for the AddEvent can get sent while the client still thinks it is
receiving the payload from the ReadResponse.  The tail of the payload
will then be read as the next message from the server.

 a) corrupt the read payload
 b) result is a bogus message

---

A minimal example to reproduce the problem is

server:

```python
#!/usr/bin/env python3

import time
from caproto.server import pvproperty, PVGroup, ioc_arg_parser, run
import numpy as np

image_shape = (3960, 3960)


class IOInterruptIOC(PVGroup):
    t1 = pvproperty(value=2.0)
    dt1 = pvproperty(value=0.9, dtype=float, precision=3)
    image = pvproperty(
        value=np.random.randint(0, 256, image_shape).flatten(), dtype=float
    )

    @t1.startup
    async def t1(self, instance, async_lib):
        # Loop and grab items from the queue one at a time
        while True:
            await self.t1.write(time.monotonic())
            await async_lib.library.sleep(0.1)


if __name__ == "__main__":
    ioc_options, run_options = ioc_arg_parser(
        default_prefix="big_image:",
        desc="Run an IOC that updates via I/O interrupt on key-press events.",
    )

    ioc = IOInterruptIOC(**ioc_options)
    print(ioc.image)
    run(ioc.pvdb, **run_options)

```

client:
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""

"""
import epics

# import caproto.threading.pyepics_compat as epics

default_prefix = "big_image:"

image = epics.PV(pvname=default_prefix + "image")
t1 = epics.PV(pvname=default_prefix + "t1")
t1.add_callback(lambda value, **kwargs: print(f"t1: {value}"))

for j in range(42):
    img = image.get(timeout=20)
    print(img.shape)

```

Not sure we want to put in a CI test for this as in is a _bit_ flaky and definitely slow.

----

attn @vstadnytskyi

### CODE REVIEW

**Comment by danielballan** [comment]
Nice quick fix! Before merging we should verify that `acctst` still runs.

**Comment by danielballan** [comment]
Could this affect the other servers? It looks like trio has a lock for this (on phone, can’t easily link...) but not sure.

**Comment by klauer** [comment]
Yes, all will need modification.

**Comment by tacaswell** [comment]
Fixed everywhere.

**Comment by tacaswell** [comment]
closes #525

**Comment by tacaswell** [comment]
I suspect I don't understand something about how timeouts propagate...

**Comment by danielballan** [comment]
The timeout propagation fix is now in #533. I'll merge that first, once CI passes, and then rebase this.

**Comment by danielballan** [comment]
One random failure:

```
caproto/tests/test_pyepics_compat.py::test_emptyish_char_waveform_no_monitor FAILED 
```

Re-running to be sure...

But `acctst` (run locally, as usual) has passed.

**Comment by danielballan** [comment]
Failure as not repeated on re-run. Merging!

**Pull request merged**
