### PR TITLE
Fix broken entry-points

### PR DESCRIPTION
**Pull request by mrakitin**
Our [profile_collection CI tests](https://github.com/NSLS-II/profile-collection-ci/blob/9a729913d22289322f3ddca72ff6aa695f4c8bf6/azure-linux.yml#L170) are using caproto's `spoof-beamline-beamline`, and they [failed](https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=1262&view=logs&j=c58b40dd-1ba0-5a8c-8e7a-987c20afdefa&t=8f1b40f4-c2fc-5e37-c197-a69f5d504b9f&l=736.) in the latest version:
```py
Traceback (most recent call last):
  File "/home/vsts/miniconda/envs/collection-2021-1.0/bin/caproto-spoof-beamline", line 6, in <module>
    from caproto.ioc_examples.spoof_beamline import main
ModuleNotFoundError: No module named 'caproto.ioc_examples.spoof_beamline'
```

This PR fixes the broken entry-points.

### CODE REVIEW

**Review by klauer — APPROVED** [review]
Good fix.

2 pathological console entrypoints upon installation. Seems apropos of caproto!

**Comment by mrakitin** [comment]
Thanks for your review, @klauer!

Forgot to mention @jklynch who discovered that error.

**Comment by klauer** [comment]
Also need to address it in conda-forge recipe for the next release: https://github.com/conda-forge/caproto-feedstock/issues/27

**Comment by mrakitin** [comment]
That's a good point. I'll add a note for `nsls2forge` too.

**Pull request merged**
